#!/usr/bin/env python3
"""
Task Execution Progress Tracker

Monitors and displays the progress of a multi-phase task execution.
Writes progress to TASK_PROGRESS.md during execution.
"""

import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional


class ProgressTracker:
    """Tracks and reports progress of task execution."""

    def __init__(self, output_dir: str):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.progress_file = self.output_dir / "TASK_PROGRESS.md"
        self.phases = {}
        self.start_time = datetime.now()
        self.current_phase = None

    def start_phase(self, phase_num: int, phase_title: str):
        """Record the start of a phase."""
        self.current_phase = phase_num
        self.phases[phase_num] = {
            'title': phase_title,
            'status': 'IN_PROGRESS',
            'start_time': datetime.now().isoformat(),
            'end_time': None,
            'duration': None,
            'findings': [],
            'files_generated': []
        }
        self.save()

    def add_finding(self, phase_num: int, finding: str):
        """Add a finding to the current phase."""
        if phase_num in self.phases:
            self.phases[phase_num]['findings'].append({
                'timestamp': datetime.now().isoformat(),
                'finding': finding
            })
            self.save()

    def add_file(self, phase_num: int, filename: str):
        """Record a file generated by a phase."""
        if phase_num in self.phases:
            self.phases[phase_num]['files_generated'].append(filename)
            self.save()

    def complete_phase(self, phase_num: int, success: bool = True):
        """Mark a phase as completed."""
        if phase_num in self.phases:
            self.phases[phase_num]['status'] = 'SUCCESS' if success else 'FAILED'
            self.phases[phase_num]['end_time'] = datetime.now().isoformat()

            start = datetime.fromisoformat(self.phases[phase_num]['start_time'])
            end = datetime.fromisoformat(self.phases[phase_num]['end_time'])
            duration_seconds = (end - start).total_seconds()
            self.phases[phase_num]['duration'] = f"{duration_seconds:.1f}s"

            self.save()

    def save(self):
        """Save progress to markdown file."""
        content = self._generate_markdown()
        self.progress_file.write_text(content, encoding='utf-8')

    def _generate_markdown(self) -> str:
        """Generate markdown progress report."""
        total_duration = (datetime.now() - self.start_time).total_seconds()
        completed = sum(1 for p in self.phases.values() if p['status'] in ['SUCCESS', 'FAILED'])
        successful = sum(1 for p in self.phases.values() if p['status'] == 'SUCCESS')

        md = f"""# Task Execution Progress

**Started:** {self.start_time.isoformat()}
**Updated:** {datetime.now().isoformat()}
**Elapsed:** {total_duration:.1f} seconds

## Status Summary

- **Completed:** {completed}/{len(self.phases)} phases
- **Successful:** {successful}/{len(self.phases)}
- **Current Phase:** {self.current_phase if self.current_phase else 'None'}

"""

        # Phase status table
        md += """## Phase Status

| Phase | Title | Status | Duration | Files |
|-------|-------|--------|----------|-------|
"""

        for phase_num in sorted(self.phases.keys()):
            phase = self.phases[phase_num]
            status_icon = {
                'IN_PROGRESS': '🔄',
                'SUCCESS': '✓',
                'FAILED': '✗'
            }.get(phase['status'], '?')

            duration = phase['duration'] or '...'
            file_count = len(phase['files_generated'])

            md += f"| {phase_num} | {phase['title']} | {status_icon} {phase['status']} | {duration} | {file_count} |\n"

        # Detailed phase info
        md += "\n## Phase Details\n\n"

        for phase_num in sorted(self.phases.keys()):
            phase = self.phases[phase_num]
            md += f"### Phase {phase_num} — {phase['title']}\n\n"
            md += f"**Status:** {phase['status']}\n\n"

            if phase['findings']:
                md += "**Findings:**\n\n"
                for finding in phase['findings']:
                    ts = finding['timestamp'].split('T')[1].split('.')[0]  # HH:MM:SS
                    md += f"- `[{ts}]` {finding['finding']}\n"
                md += "\n"

            if phase['files_generated']:
                md += "**Files Generated:**\n\n"
                for filename in phase['files_generated']:
                    md += f"- {filename}\n"
                md += "\n"

        return md


def display_progress(output_dir: str):
    """Display current progress from file."""
    progress_file = Path(output_dir) / "TASK_PROGRESS.md"
    if progress_file.exists():
        print(progress_file.read_text(encoding='utf-8'))
    else:
        print("No progress file found. Task execution may not have started.")


if __name__ == '__main__':
    import sys

    if len(sys.argv) < 2:
        print("Usage: python progress_tracker.py <output_dir> [--display]")
        sys.exit(1)

    output_dir = sys.argv[1]

    if '--display' in sys.argv:
        display_progress(output_dir)
    else:
        # Would be used internally by executor
        pass
