#!/usr/bin/env python3
"""
clockwork_version_bump — CCW-MVP21: Clockwork Versioning skill.

Reads the current Clockwork semver from .claude/VERSION, bumps it according
to bump_type (major/minor/patch), writes a date-stamped changelog entry, and
updates .claude/CHANGELOG.md header. Optionally creates a git tag.

Also implements `clockwork_changelog_entry` as a lightweight companion that
adds a single changelog line without bumping the version.

Usage (standalone):
    python3 clockwork_version_bump.py '{"skill_id":"clockwork_version_bump","inputs":{"bump_type":"minor","summary":"Added Create MVP skill","affected_mvps":["CCW-MVP20"],"dry_run":true}}'

Output (stdout JSON, SkillResultSpec):
    {"type": "skill_result_spec", "skill_id": "clockwork_version_bump", "status": "ok"|"dry_run"|"error", ...}
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import date
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parents[3]  # .claude/tools/skills/ -> repo root
_CLAUDE_DIR = _REPO_ROOT / ".claude"
_VERSION_FILE = _CLAUDE_DIR / "VERSION"
_CHANGELOG_FILE = _CLAUDE_DIR / "CHANGELOG.md"
_CHANGELOG_DIR = _CLAUDE_DIR / "changelog"


# ---------------------------------------------------------------------------
# Semver helpers
# ---------------------------------------------------------------------------

def _parse_version(ver_str: str) -> tuple[int, int, int]:
    """Parse 'MAJOR.MINOR.PATCH' into a 3-tuple of ints."""
    parts = ver_str.strip().split(".")
    if len(parts) != 3:
        raise ValueError(f"Invalid version format (expected MAJOR.MINOR.PATCH): {ver_str!r}")
    return tuple(int(p) for p in parts)  # type: ignore[return-value]


def _format_version(major: int, minor: int, patch: int) -> str:
    return f"{major}.{minor}.{patch}"


def _bump(ver_str: str, bump_type: str) -> tuple[str, str]:
    """Return (previous_version, new_version) after applying bump_type."""
    major, minor, patch = _parse_version(ver_str)
    if bump_type == "major":
        new = _format_version(major + 1, 0, 0)
    elif bump_type == "minor":
        new = _format_version(major, minor + 1, 0)
    elif bump_type == "patch":
        new = _format_version(major, minor, patch + 1)
    else:
        raise ValueError(f"bump_type must be 'major', 'minor', or 'patch'; got: {bump_type!r}")
    return ver_str.strip(), new


# ---------------------------------------------------------------------------
# Version file I/O
# ---------------------------------------------------------------------------

def _read_version() -> str:
    """Read version from .claude/VERSION. Returns '0.0.0' if file absent."""
    if not _VERSION_FILE.exists():
        return "0.0.0"
    return _VERSION_FILE.read_text(encoding="utf-8").strip()


def _write_version(version: str) -> None:
    _VERSION_FILE.write_text(version + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Changelog helpers
# ---------------------------------------------------------------------------

def _build_changelog_entry(new_version: str, summary: str,
                            affected_mvps: list[str], today: str) -> str:
    mvps_str = ", ".join(affected_mvps) if affected_mvps else "—"
    lines = [
        f"## v{new_version} — {today}",
        "",
        f"**Summary:** {summary}",
        f"**Affected MVPs:** {mvps_str}",
        "",
    ]
    return "\n".join(lines)


def _write_changelog_entry(entry_text: str, new_version: str, today: str) -> Path:
    """Append entry to a date-stamped file in .claude/changelog/."""
    _CHANGELOG_DIR.mkdir(parents=True, exist_ok=True)
    log_file = _CHANGELOG_DIR / f"changelog_{today}.md"
    with log_file.open("a", encoding="utf-8") as f:
        f.write(entry_text + "\n")
    return log_file


def _update_changelog_header(new_version: str, summary: str) -> None:
    """Prepend or update the version line in .claude/CHANGELOG.md."""
    header_line = f"<!-- current-version: {new_version} -->\n"
    if _CHANGELOG_FILE.exists():
        content = _CHANGELOG_FILE.read_text(encoding="utf-8")
        # Replace existing current-version comment if present
        import re
        content = re.sub(r"<!--\s*current-version:.*?-->\n?", "", content)
        _CHANGELOG_FILE.write_text(header_line + content, encoding="utf-8")
    else:
        _CHANGELOG_FILE.write_text(
            header_line + f"\n# Clockwork Changelog\n\n_Generated by clockwork_version_bump_\n",
            encoding="utf-8",
        )


# ---------------------------------------------------------------------------
# Git tag helper
# ---------------------------------------------------------------------------

def _create_git_tag(version: str) -> tuple[bool, str | None]:
    """Attempt to create an annotated git tag. Returns (success, error_msg)."""
    tag_name = f"v{version}"
    try:
        result = subprocess.run(
            ["git", "tag", "-a", tag_name, "-m", f"Clockwork release {tag_name}"],
            capture_output=True,
            text=True,
            cwd=str(_REPO_ROOT),
        )
        if result.returncode == 0:
            return True, None
        return False, result.stderr.strip()
    except FileNotFoundError:
        return False, "git not found in PATH"


# ---------------------------------------------------------------------------
# clockwork_version_bump
# ---------------------------------------------------------------------------

def _execute_version_bump(inputs: dict) -> dict:
    bump_type = inputs.get("bump_type", "patch")
    summary = inputs.get("summary", "")
    affected_mvps = inputs.get("affected_mvps") or []
    tag_git = bool(inputs.get("tag_git", False))
    dry_run = bool(inputs.get("dry_run", False))

    valid_bumps = {"major", "minor", "patch"}
    if bump_type not in valid_bumps:
        return {
            "previous_version": None,
            "new_version": None,
            "changelog_entry": None,
            "tag_created": False,
            "status": "error",
            "error": f"bump_type must be one of {sorted(valid_bumps)}, got: {bump_type!r}",
        }

    try:
        current = _read_version()
        previous, new_ver = _bump(current, bump_type)
    except ValueError as exc:
        return {
            "previous_version": None,
            "new_version": None,
            "changelog_entry": None,
            "tag_created": False,
            "status": "error",
            "error": str(exc),
        }

    today = date.today().isoformat()
    entry_text = _build_changelog_entry(new_ver, summary, affected_mvps, today)

    if dry_run:
        return {
            "previous_version": previous,
            "new_version": new_ver,
            "changelog_entry": entry_text,
            "tag_created": False,
            "status": "dry_run",
        }

    # Write version
    _write_version(new_ver)

    # Write changelog entry
    log_file = _write_changelog_entry(entry_text, new_ver, today)
    _update_changelog_header(new_ver, summary)

    # Optional git tag
    tag_created = False
    tag_error = None
    if tag_git:
        tag_created, tag_error = _create_git_tag(new_ver)

    result: dict = {
        "previous_version": previous,
        "new_version": new_ver,
        "changelog_entry": entry_text,
        "changelog_written_to": str(log_file),
        "tag_created": tag_created,
        "status": "ok",
    }
    if tag_error:
        result["warnings"] = [f"git tag failed: {tag_error}"]
    return result


# ---------------------------------------------------------------------------
# clockwork_changelog_entry (companion skill)
# ---------------------------------------------------------------------------

def _execute_changelog_entry(inputs: dict) -> dict:
    version = inputs.get("version", "")
    entry_text = inputs.get("entry_text", "")
    category = inputs.get("category", "added")

    valid_categories = {"added", "changed", "fixed", "removed"}
    if category not in valid_categories:
        return {
            "written_to": None,
            "status": "error",
            "error": f"category must be one of {sorted(valid_categories)}, got: {category!r}",
        }

    if not version or not entry_text:
        return {
            "written_to": None,
            "status": "error",
            "error": "version and entry_text are required",
        }

    today = date.today().isoformat()
    _CHANGELOG_DIR.mkdir(parents=True, exist_ok=True)
    log_file = _CHANGELOG_DIR / f"changelog_{today}.md"
    line = f"- [{category.upper()}] (v{version}) {entry_text}\n"
    with log_file.open("a", encoding="utf-8") as f:
        f.write(line)

    return {
        "written_to": str(log_file),
        "status": "ok",
    }


# ---------------------------------------------------------------------------
# skill_runner interface
# ---------------------------------------------------------------------------

def run(req: dict) -> dict:
    """Called by skill_runner.py with a full SkillRequestSpec."""
    skill_id = req.get("skill_id", "clockwork_version_bump")
    inputs = req.get("inputs") or req.get("input") or {}

    try:
        if skill_id == "clockwork_changelog_entry":
            result = _execute_changelog_entry(inputs)
        else:
            result = _execute_version_bump(inputs)
    except Exception as exc:
        result = {
            "status": "error",
            "error": str(exc),
        }

    return {
        "type": "skill_result_spec",
        "request_id": req.get("request_id", ""),
        "skill_id": skill_id,
        "status": result.get("status", "error"),
        "outputs": result,
        "errors": [result["error"]] if result.get("error") else [],
        "warnings": result.get("warnings", []),
        "metrics": {},
    }


# ---------------------------------------------------------------------------
# Standalone entrypoint
# ---------------------------------------------------------------------------

def main() -> int:
    if len(sys.argv) >= 2:
        raw = sys.argv[1]
    else:
        raw = sys.stdin.read()

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        sys.stderr.write(f"Invalid JSON input: {exc}\n")
        return 1

    if data.get("type") == "skill_request_spec" or "skill_id" in data:
        result = run(data)
    else:
        result = run({"inputs": data})

    sys.stdout.write(json.dumps(result, indent=2, ensure_ascii=False) + "\n")
    return 0 if result["status"] in ("ok", "dry_run") else 1


if __name__ == "__main__":
    raise SystemExit(main())
