#!/usr/bin/env python3
from __future__ import annotations

"""One-button release cut (deterministic).

Creates an evidence run, runs QA gate, builds an evidence bundle, optionally redacts it,
and writes a PackManifest.

Does NOT publish anything.
"""

import datetime
import json
from pathlib import Path

from evidence_init import run as evidence_init
from qa_gate import run as qa_gate
from evidence_bundle_build import run as evidence_bundle_build
from security_redactor import run as security_redactor


def _mk_req(skill_id: str, request_id: str, inputs: dict) -> dict:
    return {"type": "skill_request_spec", "skill_id": skill_id, "request_id": request_id, "inputs": inputs}


def run(req: dict) -> dict:
    inputs = req.get("inputs", {})
    root = Path(inputs.get("evidence_root", "validation_runs")).resolve()
    date_str = inputs.get("date") or datetime.date.today().isoformat()

    ev = evidence_init(_mk_req("evidence_init", "rel_evidence", {"root": str(root), "date": date_str}))
    if ev.get("status") != "ok":
        return {"type": "skill_result_spec", "request_id": req.get("request_id", ""), "skill_id": req.get("skill_id", "release_cut"), "status": "fail", "outputs": {"evidence": ev}, "metrics": {}, "errors": ["Failed to initialize evidence"], "warnings": []}

    run_dir = Path(ev["outputs"]["run_dir"]).resolve()

    q = qa_gate(_mk_req("qa_gate", "rel_qa", {"mode": inputs.get("mode", "gate"), "project_root": str(Path('.').resolve()), "claude_root": str(Path('.claude').resolve())}))

    gate_path = run_dir / "reports" / "qa_gate.json"
    gate_path.parent.mkdir(parents=True, exist_ok=True)
    gate_path.write_text(json.dumps(q, indent=2, ensure_ascii=False), encoding="utf-8")

    b = evidence_bundle_build(_mk_req("evidence_bundle_build", "rel_bundle", {"run_dir": str(run_dir), "project_root": str(Path('.').resolve())}))

    redacted = None
    if bool(inputs.get("redact", True)):
        redacted_out = run_dir.parent / f"{run_dir.name}_redacted"
        redacted = security_redactor(_mk_req("security_redactor", "rel_redact", {"input_dir": str(run_dir), "output_dir": str(redacted_out)}))

    pack_manifest = {
        "type": "pack_manifest",
        "run_id": run_dir.name,
        "pack_type": "docpack" if q.get("status") == "ok" else "incidentpack",
        "items": [
            {"kind": "file", "ref": "reports/qa_gate.json", "reason": "Gate result"},
            {"kind": "file", "ref": "artifacts/evidence_bundle_manifest.json", "reason": "Bundle manifest"},
            {"kind": "file", "ref": "artifacts/evidence_bundle.zip", "reason": "Evidence bundle"},
        ],
        "size_estimate_kb": float((Path(b["outputs"]["zip"]).stat().st_size if b.get("status") == "ok" else 0) / 1024.0),
        "notes": "Generated by release_cut skill",
    }

    manifest_path = run_dir / "reports" / "pack_manifest.json"
    manifest_path.write_text(json.dumps(pack_manifest, indent=2, ensure_ascii=False), encoding="utf-8")

    status = "ok" if q.get("status") == "ok" else "fail"

    return {
        "type": "skill_result_spec",
        "request_id": req.get("request_id", ""),
        "skill_id": req.get("skill_id", "release_cut"),
        "status": status,
        "outputs": {"run_dir": str(run_dir), "qa_gate": q, "bundle": b, "redaction": redacted, "pack_manifest": str(manifest_path)},
        "metrics": {"qa_ok": 1 if q.get("status") == "ok" else 0},
        "errors": ["QA gate failed"] if q.get("status") != "ok" else [],
        "warnings": [],
    }
