#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
from idea_dedupe import simple_cluster

def run(req: dict) -> dict:
    """
    Tool-side helper for creativity burst:
    - expects an input JSON containing 'ideas' as list of one-line strings (already generated by a cheap LLM)
    - clusters and selects top candidates (deterministic heuristic)
    """
    inputs = req.get("inputs", {})
    ideas = inputs.get("ideas", [])
    if not isinstance(ideas, list) or len(ideas) < 5:
        return {
            "type":"skill_result_spec",
            "request_id": req.get("request_id",""),
            "skill_id": req.get("skill_id","creativity_burst"),
            "status":"fail",
            "outputs": {},
            "metrics": {},
            "errors": ["inputs.ideas must be a list with at least 5 one-line ideas"],
            "warnings": []
        }

    clusters_idx = simple_cluster(ideas)
    clusters = []
    for ci, idxs in enumerate(clusters_idx[:12]):
        clusters.append({"label": f"cluster_{ci+1}", "idea_indexes": idxs})

    # Deterministic top picks: first idea from first 3 clusters
    top = []
    for c in clusters[:3]:
        if c["idea_indexes"]:
            top.append(c["idea_indexes"][0])

    return {
        "type":"skill_result_spec",
        "request_id": req.get("request_id",""),
        "skill_id": req.get("skill_id","creativity_burst"),
        "status":"ok",
        "outputs":{
            "clusters": clusters,
            "top_indexes": top
        },
        "metrics":{"idea_count": len(ideas), "cluster_count": len(clusters)},
        "errors":[],
        "warnings":[]
    }
